version: '3.9'
services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: vue
    environment:
      - NODE_ENV=development
    volumes:
    - ./app:/code
    ports:
    - "8080:8080"
    - "3000:3000"
